on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 12
        java-package: jdk
        architecture: x64
    - uses: DeLaGuardo/setup-clojure@master
      with:
        lein: 2.9.1

    - name: install dependencies
      run: lein deps

    - name: unit tests
      run: lein with-profile -dev test

    - name: build js
      run: lein with-profile -dev cljsbuild once min

    - name: build resume data JSON
      run: lein with-profile -dev run -m resume.json

    - name: build css
      run: lein with-profile -dev run -m resume.style

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./resources/public
